export type ApiErrorCode =
  | 'INVALID_CREDENTIALS'
  | 'ACCOUNT_BANNED'
  | 'EMAIL_ALREADY_EXISTS'
  | 'DEVICE_ALREADY_REGISTERED'
  | 'USER_NOT_FOUND'
  | 'PRIZE_NOT_FOUND'
  | 'PRIZE_OUT_OF_BOUNDS'
  | 'PRIZE_CLAIM_FAILED'
  | 'REASON_REQUIRED'
  | 'INSUFFICIENT_POINTS'
  | 'REWARD_NOT_FOUND'
  | 'REWARD_NOT_AVAILABLE'
  | 'OUT_OF_STOCK'
  | 'REDEMPTION_NOT_FOUND'
  | 'DISTANCE_TOO_FAR'
  | 'LOCATION_OUT_OF_BOUNDS'
  | 'ANTI_CHEAT_VIOLATION'
  | 'INVALID_REFRESH_TOKEN'
  | 'INVALID_PAYLOAD'
  | 'ALREADY_EXISTS'
  | 'FORBIDDEN'
  | 'UNKNOWN_ERROR';

export interface NormalizedError {
  code: ApiErrorCode;
  message: string;
}

const messageToCode: Record<string, ApiErrorCode> = {
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  ACCOUNT_BANNED: 'ACCOUNT_BANNED',
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  DEVICE_ALREADY_REGISTERED: 'DEVICE_ALREADY_REGISTERED',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  PRIZE_NOT_FOUND: 'PRIZE_NOT_FOUND',
  PRIZE_OUT_OF_BOUNDS: 'PRIZE_OUT_OF_BOUNDS',
  PRIZE_CLAIM_FAILED: 'PRIZE_CLAIM_FAILED',
  REASON_REQUIRED: 'REASON_REQUIRED',
  INSUFFICIENT_POINTS: 'INSUFFICIENT_POINTS',
  REWARD_NOT_FOUND: 'REWARD_NOT_FOUND',
  REWARD_NOT_AVAILABLE: 'REWARD_NOT_AVAILABLE',
  OUT_OF_STOCK: 'OUT_OF_STOCK',
  REDEMPTION_NOT_FOUND: 'REDEMPTION_NOT_FOUND',
  DISTANCE_TOO_FAR: 'DISTANCE_TOO_FAR',
  LOCATION_OUT_OF_BOUNDS: 'LOCATION_OUT_OF_BOUNDS',
  ANTI_CHEAT_VIOLATION: 'ANTI_CHEAT_VIOLATION',
  INVALID_REFRESH_TOKEN: 'INVALID_REFRESH_TOKEN',
  INVALID_PAYLOAD: 'INVALID_PAYLOAD',
  ALREADY_EXISTS: 'ALREADY_EXISTS',
  FORBIDDEN: 'FORBIDDEN',
};

export function normalizeError(error: unknown, fallbackMessage = 'Unexpected error'): NormalizedError {
  const rawMessage = error instanceof Error ? error.message : String(error ?? '');
  const code = messageToCode[rawMessage] || 'UNKNOWN_ERROR';
  return {
    code,
    message: code === 'UNKNOWN_ERROR' ? fallbackMessage : rawMessage,
  };
}
